PREFIX eg: <http://www.example.org/>
# LOAD <../sparql-endpoints-from-andre-status.trig>

# CONSTRUCT WHERE { GRAPH ?g { ?s ?p ?o } }


CONSTRUCT {
  GRAPH ?g {
    ?s
      eg:serviceStatus ?status ;
      eg:serviceStatusTime ?time # Note: The time refers to when the query was started
      .
  }
}
{
  BIND(NOW() AS ?time)
  BIND(IRI(CONCAT("http://metalod.aksw.org/service-check-", STR(?time))) AS ?g)

  { SELECT * {
    ?s dcat:endpointURL ?e .
    GRAPH ?ggg {
      ?s eg:serviceStatus "online"
    }
  } ORDER BY ?e LIMIT 5 }

  SERVICE SILENT ?e {
    { SELECT ?t { ?x a ?t } LIMIT 1 }
  }

  BIND(IF(BOUND(?t), "online", "offline") AS ?status)
}
