PREFIX eg: <http://www.example.org/>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX schema: <https://schema.org/>
# I once saw I comment in jena that using http as a prefix might break things, so to be safe I use just h
PREFIX h: <http://www.w3.org/2011/http#>

# CONSTRUCT WHERE { GRAPH ?g { ?s ?p ?o } }


CONSTRUCT {
  GRAPH ?g {
    ?s
      a sd:Service ;
      schema:url ?e ;
      eg:serviceStatus ?status ;
      eg:serviceStatusTime ?time ; # Note: The time refers to when the query was started
      .
  }
}
{
  BIND(NOW() AS ?time)

  GRAPH ?g { ?s dcat:endpointURL ?e }

  SERVICE SILENT ?e {
    { SELECT ?t { ?x a ?t } LIMIT 1 }
  }

  BIND(IF(BOUND(?t), "online", "offline") AS ?status)
}
